name: Working Dirs & Shells
on: [push]
jobs:
    display-wd-info:
        runs-on: ubuntu-latests
        steps:
            - name: Display Working Directory & List Fiels
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
    display-wd-info-windows:
        runs-on: windows-latests
        steps:
            - name: Display Working Directory & List Fiels
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
